server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: armsb-mock

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    sb1.stub.armsbmock: ${LOG_LEVEL_ARMSB:DEBUG}
  pattern:
    console: "${LOG_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}"
    file: "${LOG_PATTERN_FILE:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n}"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

# Swagger configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

# ARMSB Mock configuration
armsb:
  mock:
    default-delay: ${ARMSB_DEFAULT_DELAY:100}
    # Endpoint-specific delays (in milliseconds)
    # Individual properties to work around Spring Boot property mapping limitations
    delays:
      "/clients/srvgetclientlist": 150
      "/tasks/getByFilter": 200
      "/cti/getCommunications": 50
      "/clientcard/positions/get": 300
    clients:
      enabled: ${ARMSB_CLIENTS_ENABLED:true}
    tasks:
      enabled: ${ARMSB_TASKS_ENABLED:true}
    cti:
      enabled: ${ARMSB_CTI_ENABLED:true}
    client-card:
      enabled: ${ARMSB_CLIENT_CARD_ENABLED:true}